### ISSUE TITLE
Metrics for history and number of package downloads

### ISSUE THREAD

**Issue by dgkf** [pharmaR/riskmetric#52]
For central repositories that measure downloads of packages (CRAN/Bioconductor), can we produce a metric that assesses the popularity of a package based on how many downloads it gets. 

Clearly this won't be entirely rigorous as package downloads don't inherently map to package users, but surely it provides a relative measure of adoption. 

We could consider implementing multiple "views" of the same metric, for example 
- \# of packages in the past year
- \# of packages in the past few months
- month over month download growth: rate of change of downloads/day over last few month?

I'm sure we can get really creative about this. Since I think we'd likely pull down a pretty large amount of historical package download data, the different derived metrics of this data would be computationally pretty cheap so we can have some fun implementing different interpretations.

**Comment by emdserono** [comment]
How to score the number of downloads? 

1) should have values between 0 (poor practice) and 1 (best practice), which suggests logistic transformation `1 - 1 / (1 + exp(x))`
2) the total number of downloads (per year) needs to be normalized. In a small case study using R studio's quick list of useful R packages (Rstudio,<https://support.rstudio.com/hc/en-us/articles/201057987-Quick-list-of-useful-R-packages>) results in a median of around 200,000. 

Thus, I would suggest to derived the score as follows: 
```
1 - 1 / (1 + exp(x/2e6))
```
What do you think?

**Comment by emdserono** [comment]
Some examples: 

```
> score_fct <- function(x){
+   1 - 1 / (1 + exp(log(x)-log(1.5e5)))
+ }
> score_fct(9201340) # ggplot2
[1] 0.9839595
> score_fct(9509580) # dplyr
[1] 0.9844714
> score_fct(150000)  # R studio list boundary
[1] 0.5
> score_fct(10000)   # something less frequently used
[1] 0.0625
> score_fct(1000)    # rarely used
[1] 0.006622517
```

**Comment by dgkf** [comment]
Thanks, @emdserono - All really great considerations. I think something like this is definitely the way to go. Thank you very, very much for providing some context to the number of downloads and what should be a "target" number of downloads for well respected packages. I'm more of a visual person so I plotted out the function.

```r
library(dplyr)
library(ggplot2)

target = 1.5e5
score_func_a <- function(x) 1 - 1 / (1 + exp(log(x) - log(target)))
score_func_b <- function(x) 1 - 1 / (1 + (10^((log10(x) - 3.5) / 2)))

tibble(downloads = 10 ^ seq(from = 0, to = 8, by = 0.01)) %>%
  mutate(
    A = score_func_a(downloads),
    B = score_func_b(downloads)) %>%
  gather(formula, score, -downloads) %>%
  ggplot() +
    aes(x = downloads, y = score, color = formula) + 
    geom_line() + 
    geom_vline(xintercept = target, linetype = 2, alpha = 0.5) +
    scale_x_log10(limits = c(1, 1e7)) + 
    scale_y_continuous(limits = c(0, 1), breaks = seq(0, 1, 0.1))
```

![image](https://user-images.githubusercontent.com/18220321/66236090-6aaa0e00-e6a6-11e9-9086-c0ceeb8d7dfe.png)

The proposed function (A, in red) had two characteristics that felt a bit off to me:
1. There is very little resolution in the 10-10,000 downloads range. For me, this is probably where we want to focus our dynamic range.
2. Just passing the threshold set by RStudio's recommended useful packages only puts us at a score of 0.5. Presumably these are some of the best packages around if they're being hand selected for particular problem sets. 

To try to adjust for these things, I added some offsets that had the right feel to me and ended up with the function below. I aimed to have a broader tail (a bit more resolution for up-and-coming packages with 10-10,000 downloads) and to cross the cutoff from the RStudio recommended packages around a score of 0.9, which felt like a minimum score that I'd give to such well regarded packages. 

```
1 - 1 / (1 + (10^((log10(x) - 3.5) / 2)))
```

I do like the data-drivenness of your original function, @emdserono and would completely endorse it as a metric if you felt passionately about not muddying it with heuristical offsets.

**Comment by jmanitz** [comment]
Thanks @dgkf for having a look into this. I think it makes sense to be more sensitive towards "muddying it up" and played around with other conversions as well, but didnt feel brave enough to go ahead with it. This may give smaller packages a better chance to become large ;) 
I have implemented my previous version here (https://github.com/jmanitz/riskmetric). I hope to integrate your formula by the end of the week, resolve some outstanding issues (e.g add pkg_ref_cache), and create a pull request by the end of the week.

**Comment by dgkf** [comment]
Thanks @jmanitz  - I took a quick look and it's coming along really well. Thanks for taking the initiative on implementing it. Looking forward to the pull request!

**Comment by jmanitz** [comment]
Thanks @dgkf, I took you curve and played a little more to have a bit of a justification in context of the classic logistic curve: 

![image](https://user-images.githubusercontent.com/11335303/67051448-158be480-f109-11e9-8967-cb72b6a74153.png)


- we  keep the log scale for the number of downloads x=log(x)
- sigmoid midpoint is 1000 downloads x_0=log(1000)
- k=0.5 is the logistic growth rate

As a result is the target above 90% and very similar to yours

```
score_func_c <- function(x) 1 / (1 + exp(-0.5*(log(x)-log(1e3))))
```

![Rplot](https://user-images.githubusercontent.com/11335303/67050659-fb510700-f106-11e9-9aac-53796a3fa65d.png)

What do you think?

**Comment by dgkf** [comment]
That looks great. I think it's a good mix of being rooted in data, but still having the right feel for the placement of the most resolution of our dynamic range.

**Comment by elong0527** [comment]
Hi @emdserono and @jmanitz, we are setting Sprint meeting to prioritize the issues like this for Nov. 2019. Are you interested in joining the meeting and discuss further?   

Time: 2019/11/06  12PM EST 
Riskmetric repo: https://github.com/pharmaR/riskmetric
2019-11 milestone: https://github.com/pharmaR/riskmetric/milestone/3
WebX meeting link https://merck.webex.com/join/zhanyilo

**Comment by dgkf** [comment]
Going to close this one out since code was pulled in to address it with #60
